version: "3"

services:
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: passport_scorer
      POSTGRES_PASSWORD: passport_scorer_pwd
      POSTGRES_DB: passport_scorer
      PGDATA: /db_fix_trading_data

    volumes:
      - ./postgres_db_data:/db_fix_trading_data

  scorer:
    build: .
    restart: unless-stopped
    env_file: .env

    volumes:
      - ./db.sqlite3:/db.sqlite3

    ports:
      - 80:8000
